# Generated by Django 4.2.9 on 2024-08-31 18:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='media/')),
                ('tdr', models.FileField(blank=True, null=True, upload_to='tdr/')),
                ('body', tinymce.models.HTMLField()),
                ('date_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('cv', models.FileField(upload_to='candidats_docs/')),
                ('lettre_de_motivation', models.FileField(upload_to='candidats_docs/')),
                ('experience_professionnelle', models.CharField(max_length=100)),
                ('niveau_d_etude', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
    ]
