# Generated by Django 4.2.9 on 2024-08-31 19:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
