# Generated by Django 4.2.9 on 2024-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_avis_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
