# Generated by Django 4.2.9 on 2024-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_avis_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='status',
            field=models.CharField(default='Encour', max_length=100),
        ),
    ]
