# Generated by Django 4.2.9 on 2024-09-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_avis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='img',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='intro',
        ),
    ]
