# Generated by Django 4.2.15 on 2024-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.FileField(upload_to='db')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
